In [4]:
import numpy as np

def seed(seed_value):
    np.random.seed(seed_value)
    mat_1 = np.random.rand(3, 3)
    return mat_1

def matrix_arithmetic(mat_1):
    # Задайте телефонную матрицу [[1, 2, 3],[4, 5, 6],[7, 8, 9]], используя numpy
    # Выполните все поэлемнтные операции с матрицами mat_1 и mat_2:
    # сложение, вычитание из mat_1, умножение и деление mat_1

    mat_2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

    matrix_sum = mat_1 + mat_2
    matrix_diff = mat_1 - mat_2
    elementwise_product = mat_1 * mat_2
    elementwise_division = mat_1 / mat_2
    matrix_product = np.matmul(mat_1, mat_2)

    return mat_2, matrix_sum, matrix_diff, elementwise_product, elementwise_division, matrix_product

print(f"Поэлементная сумма матриц {seed(12)} и {matrix_arithmetic(seed(12))[0]} = {matrix_arithmetic(seed(12))[1]}")
print(f"Поэлементная разность матриц {seed(12)} и {matrix_arithmetic(seed(12))[0]} = {matrix_arithmetic(seed(12))[2]}")
print(f"Поэлементное произведение матриц {seed(12)} и {matrix_arithmetic(seed(12))[0]} = {matrix_arithmetic(seed(12))[3]}")
print(f"Поэлементная деление матриц {seed(12)} и {matrix_arithmetic(seed(12))[0]} = {matrix_arithmetic(seed(12))[4]}")
print(f"Матричное умножение {seed(12)} и {matrix_arithmetic(seed(12))[0]} = {matrix_arithmetic(seed(12))[5]}")

Поэлементная сумма матриц [[0.15416284 0.7400497  0.26331502]
 [0.53373939 0.01457496 0.91874701]
 [0.90071485 0.03342143 0.95694934]] и [[1 2 3]
 [4 5 6]
 [7 8 9]] = [[1.15416284 2.7400497  3.26331502]
 [4.53373939 5.01457496 6.91874701]
 [7.90071485 8.03342143 9.95694934]]
Поэлементная разность матриц [[0.15416284 0.7400497  0.26331502]
 [0.53373939 0.01457496 0.91874701]
 [0.90071485 0.03342143 0.95694934]] и [[1 2 3]
 [4 5 6]
 [7 8 9]] = [[-0.84583716 -1.2599503  -2.73668498]
 [-3.46626061 -4.98542504 -5.08125299]
 [-6.09928515 -7.96657857 -8.04305066]]
Поэлементное произведение матриц [[0.15416284 0.7400497  0.26331502]
 [0.53373939 0.01457496 0.91874701]
 [0.90071485 0.03342143 0.95694934]] и [[1 2 3]
 [4 5 6]
 [7 8 9]] = [[0.15416284 1.48009939 0.78994505]
 [2.13495757 0.07287481 5.51248205]
 [6.30500398 0.26737142 8.61254403]]
Поэлементная деление матриц [[0.15416284 0.7400497  0.26331502]
 [0.53373939 0.01457496 0.91874701]
 [0.90071485 0.03342143 0.95694934]] и [[1 2 3]
 [4 5