# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [34]:
import numpy as np

In [46]:
tm = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]) # 1
tm = tm + np.eye(3) # 2
print(tm)
v1 = np.array([1, 2, 3])
resm1 = tm * v1
resm2 = np.dot(tm, v1) # 3
print(resm2)
transposem = np.transpose(tm) # 4
print(transposem)
invm = np.linalg.inv(tm) # 5
print(invm)
tm @ invm

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
[15. 34. 53.]
[[ 2.  4.  7.]
 [ 2.  6.  8.]
 [ 3.  6. 10.]]
[[-6.00000000e+00 -2.00000000e+00  3.00000000e+00]
 [-1.00000000e+00  5.00000000e-01 -2.33146835e-16]
 [ 5.00000000e+00  1.00000000e+00 -2.00000000e+00]]


array([[ 1.00000000e+00, -3.33066907e-16,  6.66133815e-16],
       [-5.32907052e-15,  1.00000000e+00,  1.33226763e-15],
       [-1.77635684e-15, -1.11022302e-15,  1.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [36]:
m = np.array([[2, 2], [1, 3]])
print(m)
m2 = np.linalg.eig(m)
print(m2)

[[2 2]
 [1 3]]
EigResult(eigenvalues=array([1., 4.]), eigenvectors=array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]]))


### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [40]:
print(2 * 3 - 1 * 5 == 1)
hz = np.array([
    [2, 5], 
    [1, 3]])
np.linalg.det(hz)

True


1.0